### ISSUE TITLE
please update this gem on rubygems.org

### ISSUE THREAD

**Issue by vvchik** [jvoorhis/vagrant-serverspec#14]
Hi @jvoorhis 

If try to use plugin in standard way  `vagrant plugin install vagrant-serverspec`
it still downloading version 0.1.0

here current version is 0.6.0
so please upload this updated version to rubygems

also it is good practice to follow [SemVer](http://semver.org/) ruleset. And it will be good idea to change major number, to 1.0.0 for example, because of backwards incompatible changes for previously written tests that need to be rewritten, for serverspec v2 usage ruleset  :)

**Comment by jvoorhis** [comment]
Hi @vvchik,

Good suggestion regarding semver. If you send a pull request, I will accept it.

The main limitation here has been my time. If you would like to participate as a collaborator for this repo, or move the project to its own org (overkill?) please let me know.

**Comment by vvchik** [comment]
hi @jvoorhis Thank you for your proposal, I already taken it and have collaborator rights.
but not shure that it is ok to make changes without ovner.

So I maked changes regarding semver.

But main question is upgrade this gem in rubygems.org

I dont have rights to do this, so please do it by your self.

**Comment by mcallaway** [comment]
+1 for updating the gem. I lost a lot of time getting started with this module because "vagrant plugin install vagrant-serverspec" installs a non working version.

**Comment by StefanScherer** [comment]
@jvoorhis maybe this helps ( http://help.rubygems.org/discussions/problems/72-how-can-i-let-multiple-people-push-out-a-new-version-of-a-gem ) so that @vvchik can publish it.

**Comment by vvchik** [comment]
hi @jvoorhis may you please follow @StefanScherer recipe?

**Comment by jvoorhis** [comment]
Hi all,

Thanks for your patience. I've pushed version 1.0.1 to rubygems.

Can @vvchik please confirm their rubygems.org username?

On Tue, Feb 17, 2015 at 7:08 AM, Volodymyr Babchynskyy <
notifications@github.com> wrote:

> hi @jvoorhis <https://github.com/jvoorhis> may you please follow
> @StefanScherer <https://github.com/StefanScherer> recipe?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jvoorhis/vagrant-serverspec/issues/14#issuecomment-74682016>
> .
>



-- 
Jeremy Voorhis

**Comment by vvchik** [comment]
hi @jvoorhis on rubygems my username also vvchik

**Comment by conorsch** [comment]
Looks to me like this issue can be closed.
