### ISSUE TITLE
Support for AWS

### ISSUE THREAD

**Issue by gamename** [jvoorhis/vagrant-serverspec#21]
Hi,

It does not work for me on AWS.  I suspect its not supported.  Could you add support please?

Thanks.
-Tennis

**Comment by jvoorhis** [comment]
Hi Tennis,

You are right that AWS support has not been tested. Since this was never a use case of mine, I doubt I will be able to prioritize this, but pull requests are welcome!

**Comment by phiche** [comment]
I guess that could explain why all my tests are failing on AWS that succeed when using test-kitchen :(

I was hoping to avoid using test-kitchen to run serverspec, but I guess I'll have to live with it for the moment.

**Comment by phiche** [comment]
Just an update:

I switched to an ssh backend and then my tests executed and passed as expected. 

My default_helper.rb that made my serverspec tests work with this plugin simply looks like this:

```
require 'serverspec'

set :backend, :ssh
set :os, :family => 'redhat', :release => '6', :arch => 'x86_64'
```

I have had other problems with the ssh backend to work with test-kitchen however. If you are also using test-kitchen you might be interested to read my issue here:
https://github.com/test-kitchen/busser-serverspec/issues/31

**Comment by vvchik** [comment]
looks like you have workaround, so I closing that issue.
