### ISSUE TITLE
Using two serverspec suites on two separate VMs

### ISSUE THREAD

**Issue by wilkko** [jvoorhis/vagrant-serverspec#22]
I have two vm's setup like this:

```
    config.vm.define "ubuntu" do |ubuntu|
      ubuntu.vm.box = "ubuntu/vivid64"
      ubuntu.vm.provision :serverspec do |ubuntu_spec|
        ubuntu_spec.pattern = ['**/acceptance/ubuntu/**/*_spec.rb', '**/acceptance/all/**/*_spec.rb']
      end

    end

    config.vm.define "centos" do |centos|
      centos.vm.box = "opscode-centos-6.7"

      centos.vm.provision :serverspec do |centos_spec|
        centos_spec.pattern = ['**/acceptance/centos/**/*_spec.rb', '**/acceptance/all/**/*_spec.rb']
      end
    end
```

centos suite is run for CentOS VM and ubuntu suite for the Ubuntu VM. The"all" suite should be run for both VMs. Everything works fine when running 

```
vagrant provision centos --provision-with serverspec
```

or

```
vagrant provision ubuntu --provision-with serverspec
```

but when running 

```
vagrant provision --provision-with serverspec
```

it tries to run both centos and ubuntu suites in both VMs and some of the test cases of course fails.

**Comment by achaussier** [comment]
I've the same problem. After a laborious search (i'm not a Ruby developper ;)), the #23 changes works for me.

Can you try if this resolve also your problem ?

**Comment by wilkko** [comment]
How do I run Vagrant plugin from source?

**Comment by achaussier** [comment]
Hello, I've do my checks with manual modification of installed gem with these lines.
Perhaps a better (or more delicate) method but no time to search :)

**Comment by wilkko** [comment]
Was this or the related fix released?

**Comment by vvchik** [comment]
yes, you may retry
