### ISSUE TITLE
Add ``require "net/ssh"`` inside the plugin somewhere

### ISSUE THREAD

**Issue by LucianU** [jvoorhis/vagrant-serverspec#9]
I'm not experienced enough with Ruby to offer a more specific solution, but Vagrant raises an error, because of this missing ``require``.

**Comment by vvchik** [comment]
Hi, it is already exists in [plugin.rb]
(https://github.com/jvoorhis/vagrant-serverspec/blob/master/lib/vagrant-serverspec/plugin.rb)
also you may use that in [spec_helper.rb] (https://github.com/jvoorhis/vagrant-serverspec/blob/master/test/ubuntu/spec_helper.rb) file
